### ISSUE TITLE
New Project Button CSS

### ISSUE THREAD

**Issue by param-s-8** [D-VPN/Intelligent-Document-Analyzer#8]
Debug Why The Button Turns Out To Be So Crumbled When There Are No Projects.

**Comment by param-s-8** [comment]
Then:
![image](https://user-images.githubusercontent.com/59571953/154793802-ef7315b1-32ea-466b-a577-050e0e0c4391.png)

Now:
![image](https://user-images.githubusercontent.com/59571953/154793717-cc1b7ab6-64df-402a-9e17-23708e6789b0.png)

**Comment by darshansatra1** [comment]
The button doesn't look centred, and can you change the colour to blue?

**Comment by param-s-8** [comment]
Looks Good Now?
![image](https://user-images.githubusercontent.com/59571953/154794215-58f6d0c0-0f8e-4bcf-a3dc-afe852c2fe98.png)
